"""add path

Revision ID: 4fbaa0233044
Revises: fb4fd6786ee3
Create Date: 2024-12-18 09:19:40.431524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbaa0233044'
down_revision: Union[str, None] = 'fb4fd6786ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('path', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'path')
    # ### end Alembic commands ###
