"""xiu gai role table

Revision ID: f06b4e6fe746
Revises: fa17e429dbfe
Create Date: 2025-01-21 15:53:13.839094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06b4e6fe746'
down_revision: Union[str, None] = 'fa17e429dbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('game_id', sa.Integer(), nullable=True))
    op.drop_column('role', 'game_row')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('game_row', sa.INTEGER(), nullable=True))
    op.drop_column('role', 'game_id')
    # ### end Alembic commands ###
